### ISSUE TITLE
Research frontend frameworks (02/19-22)

### ISSUE THREAD

**Issue by wjorda** [cs-4284-capstone/artist-frontend#3]
Need to do research on frontend frameworks and decide on which is best for our project.

**Comment by Thing342** [comment]
Looked at the following frameworks:
* Vue
 - Pros

**Comment by wjorda** [comment]
Did some research on frontend JS frameworks:
- React
    - Pros:
        - Familiar, I've used it before and have a good idea as to how to set it up.
        - Functional, easy to catch errors and understand data flow
        - Lots of users, so documentation is easy to find and tooling is pretty good, lots of libraries
    - Cons
        - Facebook, uncertainties around licensing
        - _How do I get this f**ing list to redraw_
        - Slow
        - Javascript, though Typescript is getting pretty good now

**Comment by wjorda** [comment]
- Vue
    - Pros
        - MIT License
        - Similar to React, familiar enough
        - Single-file-components bring styling, templates, and scripting into one file
        - Fast, compiles down to small bundle
        - State management (Vuex) is easier to grok than Redux
        - Doesn't use JSX
    - Cons
        - Typescript support still a WIP
        - Component declarations not exactly ergonomic, though this can be improved via decorators
        - Setting up SFCs is a PITA

**Comment by wjorda** [comment]
- Elm
   - Pros:
        - Purely functional, advertises no runtime exceptions
        - Not Javascript, generally not dependent on NPM fever swamps
        - Fastest of frameworks tested
    - Cons:
        - API still very unstable, has not had major release; 0.19.0 had many breaking changes and made language too opinionated IMO
        - JS interop required and is bad
        - Architecture punishes you from deviating from TEA structure
        - Not well-known, tooling is bad and libraries are sparse

**Comment by wjorda** [comment]
Based on further research and testing, it looks like Vue works the best for this project.
